/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getName <em>Name</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getVariabledeclaration <em>Variabledeclaration</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getDomain <em>Domain</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getRoundlist <em>Roundlist</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getInv <em>Inv</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Algorithm#getUv <em>Uv</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm()
 * @model
 * @generated
 */
public interface Algorithm extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Variabledeclaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variabledeclaration</em>' containment reference.
   * @see #setVariabledeclaration(VarialbeDeclaration)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Variabledeclaration()
   * @model containment="true"
   * @generated
   */
  VarialbeDeclaration getVariabledeclaration();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getVariabledeclaration <em>Variabledeclaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variabledeclaration</em>' containment reference.
   * @see #getVariabledeclaration()
   * @generated
   */
  void setVariabledeclaration(VarialbeDeclaration value);

  /**
   * Returns the value of the '<em><b>Domain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain</em>' containment reference.
   * @see #setDomain(Domain)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Domain()
   * @model containment="true"
   * @generated
   */
  Domain getDomain();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getDomain <em>Domain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Domain</em>' containment reference.
   * @see #getDomain()
   * @generated
   */
  void setDomain(Domain value);

  /**
   * Returns the value of the '<em><b>Roundlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Roundlist</em>' containment reference.
   * @see #setRoundlist(RoundList)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Roundlist()
   * @model containment="true"
   * @generated
   */
  RoundList getRoundlist();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getRoundlist <em>Roundlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Roundlist</em>' containment reference.
   * @see #getRoundlist()
   * @generated
   */
  void setRoundlist(RoundList value);

  /**
   * Returns the value of the '<em><b>Inv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inv</em>' containment reference.
   * @see #setInv(Invariant)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Inv()
   * @model containment="true"
   * @generated
   */
  Invariant getInv();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getInv <em>Inv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inv</em>' containment reference.
   * @see #getInv()
   * @generated
   */
  void setInv(Invariant value);

  /**
   * Returns the value of the '<em><b>Uv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uv</em>' containment reference.
   * @see #setUv(Univalence)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getAlgorithm_Uv()
   * @model containment="true"
   * @generated
   */
  Univalence getUv();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Algorithm#getUv <em>Uv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uv</em>' containment reference.
   * @see #getUv()
   * @generated
   */
  void setUv(Univalence value);

} // Algorithm
