/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getArrayVariable()
 * @model
 * @generated
 */
public interface ArrayVariable extends Variable
{
} // ArrayVariable
