/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getAssignment()
 * @model
 * @generated
 */
public interface Assignment extends Statement
{
} // Assignment
