/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getDecision()
 * @model
 * @generated
 */
public interface Decision extends Statement
{
} // Decision
