/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.consensus.homodel.hOModel.HOModelFactory
 * @model kind="package"
 * @generated
 */
public interface HOModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "hOModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.consensus.org/homodel/HOModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "hOModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HOModelPackage eINSTANCE = org.consensus.homodel.hOModel.impl.HOModelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.AlgorithmImpl <em>Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.AlgorithmImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__NAME = 0;

  /**
   * The feature id for the '<em><b>Variabledeclaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__VARIABLEDECLARATION = 1;

  /**
   * The feature id for the '<em><b>Domain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__DOMAIN = 2;

  /**
   * The feature id for the '<em><b>Roundlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__ROUNDLIST = 3;

  /**
   * The feature id for the '<em><b>Inv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__INV = 4;

  /**
   * The feature id for the '<em><b>Uv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__UV = 5;

  /**
   * The number of structural features of the '<em>Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.VarialbeDeclarationImpl <em>Varialbe Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.VarialbeDeclarationImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVarialbeDeclaration()
   * @generated
   */
  int VARIALBE_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIALBE_DECLARATION__LIST = 0;

  /**
   * The number of structural features of the '<em>Varialbe Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIALBE_DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.VariableDecListImpl <em>Variable Dec List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.VariableDecListImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariableDecList()
   * @generated
   */
  int VARIABLE_DEC_LIST = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEC_LIST__TYPE = 0;

  /**
   * The feature id for the '<em><b>Variablenamelist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEC_LIST__VARIABLENAMELIST = 1;

  /**
   * The number of structural features of the '<em>Variable Dec List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DEC_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.VariableNameListImpl <em>Variable Name List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.VariableNameListImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariableNameList()
   * @generated
   */
  int VARIABLE_NAME_LIST = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_NAME_LIST__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_NAME_LIST__VALUE = 1;

  /**
   * The number of structural features of the '<em>Variable Name List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_NAME_LIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.DomainImpl <em>Domain</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.DomainImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getDomain()
   * @generated
   */
  int DOMAIN = 4;

  /**
   * The number of structural features of the '<em>Domain</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.RoundListImpl <em>Round List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.RoundListImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRoundList()
   * @generated
   */
  int ROUND_LIST = 5;

  /**
   * The feature id for the '<em><b>Round</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUND_LIST__ROUND = 0;

  /**
   * The number of structural features of the '<em>Round List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUND_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.RoundImpl <em>Round</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.RoundImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRound()
   * @generated
   */
  int ROUND = 6;

  /**
   * The feature id for the '<em><b>Send</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUND__SEND = 0;

  /**
   * The feature id for the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUND__TRANSITION = 1;

  /**
   * The number of structural features of the '<em>Round</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROUND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.SendPartImpl <em>Send Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.SendPartImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getSendPart()
   * @generated
   */
  int SEND_PART = 7;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_PART__EXP = 0;

  /**
   * The feature id for the '<em><b>Message1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_PART__MESSAGE1 = 1;

  /**
   * The feature id for the '<em><b>Message2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_PART__MESSAGE2 = 2;

  /**
   * The feature id for the '<em><b>Message</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_PART__MESSAGE = 3;

  /**
   * The number of structural features of the '<em>Send Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEND_PART_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.MessageImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 8;

  /**
   * The feature id for the '<em><b>Msg</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MSG = 0;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.TransitionPartImpl <em>Transition Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.TransitionPartImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getTransitionPart()
   * @generated
   */
  int TRANSITION_PART = 9;

  /**
   * The number of structural features of the '<em>Transition Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_PART_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.InvariantImpl <em>Invariant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.InvariantImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getInvariant()
   * @generated
   */
  int INVARIANT = 10;

  /**
   * The number of structural features of the '<em>Invariant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVARIANT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.UnivalenceImpl <em>Univalence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.UnivalenceImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getUnivalence()
   * @generated
   */
  int UNIVALENCE = 11;

  /**
   * The number of structural features of the '<em>Univalence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIVALENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.StatementListImpl <em>Statement List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.StatementListImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getStatementList()
   * @generated
   */
  int STATEMENT_LIST = 12;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_LIST__VAR = DOMAIN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_LIST__EXP = DOMAIN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_LIST__STATEMENT = DOMAIN_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_LIST__STATEMENTS = DOMAIN_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Statement List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_LIST_FEATURE_COUNT = DOMAIN_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.StatementImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 13;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VAR = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__EXP = 1;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.AssignmentImpl <em>Assignment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.AssignmentImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getAssignment()
   * @generated
   */
  int ASSIGNMENT = 14;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__VAR = STATEMENT__VAR;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__EXP = STATEMENT__EXP;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT__STATEMENT = STATEMENT__STATEMENT;

  /**
   * The number of structural features of the '<em>Assignment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.FactorImpl <em>Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.FactorImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getFactor()
   * @generated
   */
  int FACTOR = 25;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__EXP = 0;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__VAR = 1;

  /**
   * The number of structural features of the '<em>Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.VariableImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 15;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__EXP = FACTOR__EXP;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VAR = FACTOR__VAR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = FACTOR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = FACTOR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.NormalVariableImpl <em>Normal Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.NormalVariableImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getNormalVariable()
   * @generated
   */
  int NORMAL_VARIABLE = 16;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VARIABLE__EXP = VARIABLE__EXP;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VARIABLE__VAR = VARIABLE__VAR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VARIABLE__NAME = VARIABLE__NAME;

  /**
   * The number of structural features of the '<em>Normal Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_VARIABLE_FEATURE_COUNT = VARIABLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.ArrayVariableImpl <em>Array Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.ArrayVariableImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getArrayVariable()
   * @generated
   */
  int ARRAY_VARIABLE = 17;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VARIABLE__EXP = VARIABLE__EXP;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VARIABLE__VAR = VARIABLE__VAR;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VARIABLE__NAME = VARIABLE__NAME;

  /**
   * The number of structural features of the '<em>Array Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_VARIABLE_FEATURE_COUNT = VARIABLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.DecisionImpl <em>Decision</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.DecisionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getDecision()
   * @generated
   */
  int DECISION = 18;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__VAR = STATEMENT__VAR;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__EXP = STATEMENT__EXP;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__STATEMENT = STATEMENT__STATEMENT;

  /**
   * The number of structural features of the '<em>Decision</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.ExpressionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 19;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VAR = STATEMENT__VAR;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXP = STATEMENT__EXP;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__STATEMENT = STATEMENT__STATEMENT;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.ConjunctiveExpressionImpl <em>Conjunctive Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.ConjunctiveExpressionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getConjunctiveExpression()
   * @generated
   */
  int CONJUNCTIVE_EXPRESSION = 20;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONJUNCTIVE_EXPRESSION__EXP = 0;

  /**
   * The number of structural features of the '<em>Conjunctive Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONJUNCTIVE_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.EqualityExpressionImpl <em>Equality Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.EqualityExpressionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getEqualityExpression()
   * @generated
   */
  int EQUALITY_EXPRESSION = 21;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_EXPRESSION__EXP = 0;

  /**
   * The number of structural features of the '<em>Equality Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.RelationalExpressionImpl <em>Relational Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.RelationalExpressionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRelationalExpression()
   * @generated
   */
  int RELATIONAL_EXPRESSION = 22;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION__EXP = 0;

  /**
   * The number of structural features of the '<em>Relational Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.SimpleExpressionImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getSimpleExpression()
   * @generated
   */
  int SIMPLE_EXPRESSION = 23;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_EXPRESSION__TERM = 0;

  /**
   * The number of structural features of the '<em>Simple Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_EXPRESSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.consensus.homodel.hOModel.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.consensus.homodel.hOModel.impl.TermImpl
   * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getTerm()
   * @generated
   */
  int TERM = 24;

  /**
   * The feature id for the '<em><b>Factor</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__FACTOR = 0;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm
   * @generated
   */
  EClass getAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link org.consensus.homodel.hOModel.Algorithm#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getName()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Algorithm#getVariabledeclaration <em>Variabledeclaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variabledeclaration</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getVariabledeclaration()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Variabledeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Algorithm#getDomain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Domain</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getDomain()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Domain();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Algorithm#getRoundlist <em>Roundlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Roundlist</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getRoundlist()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Roundlist();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Algorithm#getInv <em>Inv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inv</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getInv()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Inv();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Algorithm#getUv <em>Uv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Uv</em>'.
   * @see org.consensus.homodel.hOModel.Algorithm#getUv()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Uv();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.VarialbeDeclaration <em>Varialbe Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Varialbe Declaration</em>'.
   * @see org.consensus.homodel.hOModel.VarialbeDeclaration
   * @generated
   */
  EClass getVarialbeDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.VarialbeDeclaration#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>List</em>'.
   * @see org.consensus.homodel.hOModel.VarialbeDeclaration#getList()
   * @see #getVarialbeDeclaration()
   * @generated
   */
  EReference getVarialbeDeclaration_List();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.VariableDecList <em>Variable Dec List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Dec List</em>'.
   * @see org.consensus.homodel.hOModel.VariableDecList
   * @generated
   */
  EClass getVariableDecList();

  /**
   * Returns the meta object for the attribute '{@link org.consensus.homodel.hOModel.VariableDecList#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.consensus.homodel.hOModel.VariableDecList#getType()
   * @see #getVariableDecList()
   * @generated
   */
  EAttribute getVariableDecList_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.VariableDecList#getVariablenamelist <em>Variablenamelist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variablenamelist</em>'.
   * @see org.consensus.homodel.hOModel.VariableDecList#getVariablenamelist()
   * @see #getVariableDecList()
   * @generated
   */
  EReference getVariableDecList_Variablenamelist();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.VariableNameList <em>Variable Name List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Name List</em>'.
   * @see org.consensus.homodel.hOModel.VariableNameList
   * @generated
   */
  EClass getVariableNameList();

  /**
   * Returns the meta object for the attribute list '{@link org.consensus.homodel.hOModel.VariableNameList#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Name</em>'.
   * @see org.consensus.homodel.hOModel.VariableNameList#getName()
   * @see #getVariableNameList()
   * @generated
   */
  EAttribute getVariableNameList_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.consensus.homodel.hOModel.VariableNameList#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.consensus.homodel.hOModel.VariableNameList#getValue()
   * @see #getVariableNameList()
   * @generated
   */
  EAttribute getVariableNameList_Value();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Domain <em>Domain</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domain</em>'.
   * @see org.consensus.homodel.hOModel.Domain
   * @generated
   */
  EClass getDomain();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.RoundList <em>Round List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Round List</em>'.
   * @see org.consensus.homodel.hOModel.RoundList
   * @generated
   */
  EClass getRoundList();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.RoundList#getRound <em>Round</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Round</em>'.
   * @see org.consensus.homodel.hOModel.RoundList#getRound()
   * @see #getRoundList()
   * @generated
   */
  EReference getRoundList_Round();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Round <em>Round</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Round</em>'.
   * @see org.consensus.homodel.hOModel.Round
   * @generated
   */
  EClass getRound();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Round#getSend <em>Send</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Send</em>'.
   * @see org.consensus.homodel.hOModel.Round#getSend()
   * @see #getRound()
   * @generated
   */
  EReference getRound_Send();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.Round#getTransition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transition</em>'.
   * @see org.consensus.homodel.hOModel.Round#getTransition()
   * @see #getRound()
   * @generated
   */
  EReference getRound_Transition();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.SendPart <em>Send Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Send Part</em>'.
   * @see org.consensus.homodel.hOModel.SendPart
   * @generated
   */
  EClass getSendPart();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.SendPart#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.SendPart#getExp()
   * @see #getSendPart()
   * @generated
   */
  EReference getSendPart_Exp();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.SendPart#getMessage1 <em>Message1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Message1</em>'.
   * @see org.consensus.homodel.hOModel.SendPart#getMessage1()
   * @see #getSendPart()
   * @generated
   */
  EReference getSendPart_Message1();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.SendPart#getMessage2 <em>Message2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Message2</em>'.
   * @see org.consensus.homodel.hOModel.SendPart#getMessage2()
   * @see #getSendPart()
   * @generated
   */
  EReference getSendPart_Message2();

  /**
   * Returns the meta object for the containment reference '{@link org.consensus.homodel.hOModel.SendPart#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Message</em>'.
   * @see org.consensus.homodel.hOModel.SendPart#getMessage()
   * @see #getSendPart()
   * @generated
   */
  EReference getSendPart_Message();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see org.consensus.homodel.hOModel.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute list '{@link org.consensus.homodel.hOModel.Message#getMsg <em>Msg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Msg</em>'.
   * @see org.consensus.homodel.hOModel.Message#getMsg()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_Msg();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.TransitionPart <em>Transition Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Part</em>'.
   * @see org.consensus.homodel.hOModel.TransitionPart
   * @generated
   */
  EClass getTransitionPart();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Invariant <em>Invariant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Invariant</em>'.
   * @see org.consensus.homodel.hOModel.Invariant
   * @generated
   */
  EClass getInvariant();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Univalence <em>Univalence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Univalence</em>'.
   * @see org.consensus.homodel.hOModel.Univalence
   * @generated
   */
  EClass getUnivalence();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.StatementList <em>Statement List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement List</em>'.
   * @see org.consensus.homodel.hOModel.StatementList
   * @generated
   */
  EClass getStatementList();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.StatementList#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.consensus.homodel.hOModel.StatementList#getStatements()
   * @see #getStatementList()
   * @generated
   */
  EReference getStatementList_Statements();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.consensus.homodel.hOModel.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Statement#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var</em>'.
   * @see org.consensus.homodel.hOModel.Statement#getVar()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Var();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Statement#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.Statement#getExp()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Statement#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see org.consensus.homodel.hOModel.Statement#getStatement()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Statement();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Assignment <em>Assignment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment</em>'.
   * @see org.consensus.homodel.hOModel.Assignment
   * @generated
   */
  EClass getAssignment();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.consensus.homodel.hOModel.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.consensus.homodel.hOModel.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.consensus.homodel.hOModel.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.NormalVariable <em>Normal Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Variable</em>'.
   * @see org.consensus.homodel.hOModel.NormalVariable
   * @generated
   */
  EClass getNormalVariable();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.ArrayVariable <em>Array Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Variable</em>'.
   * @see org.consensus.homodel.hOModel.ArrayVariable
   * @generated
   */
  EClass getArrayVariable();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Decision <em>Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision</em>'.
   * @see org.consensus.homodel.hOModel.Decision
   * @generated
   */
  EClass getDecision();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.consensus.homodel.hOModel.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.ConjunctiveExpression <em>Conjunctive Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conjunctive Expression</em>'.
   * @see org.consensus.homodel.hOModel.ConjunctiveExpression
   * @generated
   */
  EClass getConjunctiveExpression();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.ConjunctiveExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.ConjunctiveExpression#getExp()
   * @see #getConjunctiveExpression()
   * @generated
   */
  EReference getConjunctiveExpression_Exp();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.EqualityExpression <em>Equality Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality Expression</em>'.
   * @see org.consensus.homodel.hOModel.EqualityExpression
   * @generated
   */
  EClass getEqualityExpression();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.EqualityExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.EqualityExpression#getExp()
   * @see #getEqualityExpression()
   * @generated
   */
  EReference getEqualityExpression_Exp();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.RelationalExpression <em>Relational Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relational Expression</em>'.
   * @see org.consensus.homodel.hOModel.RelationalExpression
   * @generated
   */
  EClass getRelationalExpression();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.RelationalExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.RelationalExpression#getExp()
   * @see #getRelationalExpression()
   * @generated
   */
  EReference getRelationalExpression_Exp();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.SimpleExpression <em>Simple Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Expression</em>'.
   * @see org.consensus.homodel.hOModel.SimpleExpression
   * @generated
   */
  EClass getSimpleExpression();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.SimpleExpression#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Term</em>'.
   * @see org.consensus.homodel.hOModel.SimpleExpression#getTerm()
   * @see #getSimpleExpression()
   * @generated
   */
  EReference getSimpleExpression_Term();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see org.consensus.homodel.hOModel.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Term#getFactor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Factor</em>'.
   * @see org.consensus.homodel.hOModel.Term#getFactor()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Factor();

  /**
   * Returns the meta object for class '{@link org.consensus.homodel.hOModel.Factor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor</em>'.
   * @see org.consensus.homodel.hOModel.Factor
   * @generated
   */
  EClass getFactor();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Factor#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp</em>'.
   * @see org.consensus.homodel.hOModel.Factor#getExp()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link org.consensus.homodel.hOModel.Factor#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var</em>'.
   * @see org.consensus.homodel.hOModel.Factor#getVar()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Var();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HOModelFactory getHOModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.AlgorithmImpl <em>Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.AlgorithmImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getAlgorithm()
     * @generated
     */
    EClass ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__NAME = eINSTANCE.getAlgorithm_Name();

    /**
     * The meta object literal for the '<em><b>Variabledeclaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__VARIABLEDECLARATION = eINSTANCE.getAlgorithm_Variabledeclaration();

    /**
     * The meta object literal for the '<em><b>Domain</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__DOMAIN = eINSTANCE.getAlgorithm_Domain();

    /**
     * The meta object literal for the '<em><b>Roundlist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__ROUNDLIST = eINSTANCE.getAlgorithm_Roundlist();

    /**
     * The meta object literal for the '<em><b>Inv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__INV = eINSTANCE.getAlgorithm_Inv();

    /**
     * The meta object literal for the '<em><b>Uv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__UV = eINSTANCE.getAlgorithm_Uv();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.VarialbeDeclarationImpl <em>Varialbe Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.VarialbeDeclarationImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVarialbeDeclaration()
     * @generated
     */
    EClass VARIALBE_DECLARATION = eINSTANCE.getVarialbeDeclaration();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIALBE_DECLARATION__LIST = eINSTANCE.getVarialbeDeclaration_List();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.VariableDecListImpl <em>Variable Dec List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.VariableDecListImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariableDecList()
     * @generated
     */
    EClass VARIABLE_DEC_LIST = eINSTANCE.getVariableDecList();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DEC_LIST__TYPE = eINSTANCE.getVariableDecList_Type();

    /**
     * The meta object literal for the '<em><b>Variablenamelist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DEC_LIST__VARIABLENAMELIST = eINSTANCE.getVariableDecList_Variablenamelist();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.VariableNameListImpl <em>Variable Name List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.VariableNameListImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariableNameList()
     * @generated
     */
    EClass VARIABLE_NAME_LIST = eINSTANCE.getVariableNameList();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_NAME_LIST__NAME = eINSTANCE.getVariableNameList_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_NAME_LIST__VALUE = eINSTANCE.getVariableNameList_Value();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.DomainImpl <em>Domain</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.DomainImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getDomain()
     * @generated
     */
    EClass DOMAIN = eINSTANCE.getDomain();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.RoundListImpl <em>Round List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.RoundListImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRoundList()
     * @generated
     */
    EClass ROUND_LIST = eINSTANCE.getRoundList();

    /**
     * The meta object literal for the '<em><b>Round</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUND_LIST__ROUND = eINSTANCE.getRoundList_Round();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.RoundImpl <em>Round</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.RoundImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRound()
     * @generated
     */
    EClass ROUND = eINSTANCE.getRound();

    /**
     * The meta object literal for the '<em><b>Send</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUND__SEND = eINSTANCE.getRound_Send();

    /**
     * The meta object literal for the '<em><b>Transition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROUND__TRANSITION = eINSTANCE.getRound_Transition();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.SendPartImpl <em>Send Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.SendPartImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getSendPart()
     * @generated
     */
    EClass SEND_PART = eINSTANCE.getSendPart();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_PART__EXP = eINSTANCE.getSendPart_Exp();

    /**
     * The meta object literal for the '<em><b>Message1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_PART__MESSAGE1 = eINSTANCE.getSendPart_Message1();

    /**
     * The meta object literal for the '<em><b>Message2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_PART__MESSAGE2 = eINSTANCE.getSendPart_Message2();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEND_PART__MESSAGE = eINSTANCE.getSendPart_Message();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.MessageImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Msg</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MSG = eINSTANCE.getMessage_Msg();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.TransitionPartImpl <em>Transition Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.TransitionPartImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getTransitionPart()
     * @generated
     */
    EClass TRANSITION_PART = eINSTANCE.getTransitionPart();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.InvariantImpl <em>Invariant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.InvariantImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getInvariant()
     * @generated
     */
    EClass INVARIANT = eINSTANCE.getInvariant();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.UnivalenceImpl <em>Univalence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.UnivalenceImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getUnivalence()
     * @generated
     */
    EClass UNIVALENCE = eINSTANCE.getUnivalence();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.StatementListImpl <em>Statement List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.StatementListImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getStatementList()
     * @generated
     */
    EClass STATEMENT_LIST = eINSTANCE.getStatementList();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT_LIST__STATEMENTS = eINSTANCE.getStatementList_Statements();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.StatementImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__VAR = eINSTANCE.getStatement_Var();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__EXP = eINSTANCE.getStatement_Exp();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__STATEMENT = eINSTANCE.getStatement_Statement();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.AssignmentImpl <em>Assignment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.AssignmentImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getAssignment()
     * @generated
     */
    EClass ASSIGNMENT = eINSTANCE.getAssignment();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.VariableImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.NormalVariableImpl <em>Normal Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.NormalVariableImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getNormalVariable()
     * @generated
     */
    EClass NORMAL_VARIABLE = eINSTANCE.getNormalVariable();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.ArrayVariableImpl <em>Array Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.ArrayVariableImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getArrayVariable()
     * @generated
     */
    EClass ARRAY_VARIABLE = eINSTANCE.getArrayVariable();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.DecisionImpl <em>Decision</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.DecisionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getDecision()
     * @generated
     */
    EClass DECISION = eINSTANCE.getDecision();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.ExpressionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.ConjunctiveExpressionImpl <em>Conjunctive Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.ConjunctiveExpressionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getConjunctiveExpression()
     * @generated
     */
    EClass CONJUNCTIVE_EXPRESSION = eINSTANCE.getConjunctiveExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONJUNCTIVE_EXPRESSION__EXP = eINSTANCE.getConjunctiveExpression_Exp();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.EqualityExpressionImpl <em>Equality Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.EqualityExpressionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getEqualityExpression()
     * @generated
     */
    EClass EQUALITY_EXPRESSION = eINSTANCE.getEqualityExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY_EXPRESSION__EXP = eINSTANCE.getEqualityExpression_Exp();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.RelationalExpressionImpl <em>Relational Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.RelationalExpressionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getRelationalExpression()
     * @generated
     */
    EClass RELATIONAL_EXPRESSION = eINSTANCE.getRelationalExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_EXPRESSION__EXP = eINSTANCE.getRelationalExpression_Exp();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.SimpleExpressionImpl <em>Simple Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.SimpleExpressionImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getSimpleExpression()
     * @generated
     */
    EClass SIMPLE_EXPRESSION = eINSTANCE.getSimpleExpression();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_EXPRESSION__TERM = eINSTANCE.getSimpleExpression_Term();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.TermImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '<em><b>Factor</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__FACTOR = eINSTANCE.getTerm_Factor();

    /**
     * The meta object literal for the '{@link org.consensus.homodel.hOModel.impl.FactorImpl <em>Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.consensus.homodel.hOModel.impl.FactorImpl
     * @see org.consensus.homodel.hOModel.impl.HOModelPackageImpl#getFactor()
     * @generated
     */
    EClass FACTOR = eINSTANCE.getFactor();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__EXP = eINSTANCE.getFactor_Exp();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__VAR = eINSTANCE.getFactor_Var();

  }

} //HOModelPackage
