/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getNormalVariable()
 * @model
 * @generated
 */
public interface NormalVariable extends Variable
{
} // NormalVariable
