/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Round</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.Round#getSend <em>Send</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.Round#getTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getRound()
 * @model
 * @generated
 */
public interface Round extends EObject
{
  /**
   * Returns the value of the '<em><b>Send</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Send</em>' containment reference.
   * @see #setSend(SendPart)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getRound_Send()
   * @model containment="true"
   * @generated
   */
  SendPart getSend();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Round#getSend <em>Send</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Send</em>' containment reference.
   * @see #getSend()
   * @generated
   */
  void setSend(SendPart value);

  /**
   * Returns the value of the '<em><b>Transition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' containment reference.
   * @see #setTransition(TransitionPart)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getRound_Transition()
   * @model containment="true"
   * @generated
   */
  TransitionPart getTransition();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.Round#getTransition <em>Transition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' containment reference.
   * @see #getTransition()
   * @generated
   */
  void setTransition(TransitionPart value);

} // Round
