/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Round List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.RoundList#getRound <em>Round</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getRoundList()
 * @model
 * @generated
 */
public interface RoundList extends EObject
{
  /**
   * Returns the value of the '<em><b>Round</b></em>' containment reference list.
   * The list contents are of type {@link org.consensus.homodel.hOModel.Round}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Round</em>' containment reference list.
   * @see org.consensus.homodel.hOModel.HOModelPackage#getRoundList_Round()
   * @model containment="true"
   * @generated
   */
  EList<Round> getRound();

} // RoundList
