/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Send Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.SendPart#getExp <em>Exp</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.SendPart#getMessage1 <em>Message1</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.SendPart#getMessage2 <em>Message2</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.SendPart#getMessage <em>Message</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getSendPart()
 * @model
 * @generated
 */
public interface SendPart extends EObject
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getSendPart_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.SendPart#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

  /**
   * Returns the value of the '<em><b>Message1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message1</em>' containment reference.
   * @see #setMessage1(Message)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getSendPart_Message1()
   * @model containment="true"
   * @generated
   */
  Message getMessage1();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.SendPart#getMessage1 <em>Message1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message1</em>' containment reference.
   * @see #getMessage1()
   * @generated
   */
  void setMessage1(Message value);

  /**
   * Returns the value of the '<em><b>Message2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message2</em>' containment reference.
   * @see #setMessage2(Message)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getSendPart_Message2()
   * @model containment="true"
   * @generated
   */
  Message getMessage2();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.SendPart#getMessage2 <em>Message2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message2</em>' containment reference.
   * @see #getMessage2()
   * @generated
   */
  void setMessage2(Message value);

  /**
   * Returns the value of the '<em><b>Message</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' containment reference.
   * @see #setMessage(Message)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getSendPart_Message()
   * @model containment="true"
   * @generated
   */
  Message getMessage();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.SendPart#getMessage <em>Message</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' containment reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(Message value);

} // SendPart
