/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.StatementList#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getStatementList()
 * @model
 * @generated
 */
public interface StatementList extends Domain, TransitionPart, Invariant, Univalence, Statement
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.consensus.homodel.hOModel.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.consensus.homodel.hOModel.HOModelPackage#getStatementList_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // StatementList
