/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Univalence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getUnivalence()
 * @model
 * @generated
 */
public interface Univalence extends EObject
{
} // Univalence
