/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Varialbe Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.VarialbeDeclaration#getList <em>List</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getVarialbeDeclaration()
 * @model
 * @generated
 */
public interface VarialbeDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference list.
   * The list contents are of type {@link org.consensus.homodel.hOModel.VariableDecList}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference list.
   * @see org.consensus.homodel.hOModel.HOModelPackage#getVarialbeDeclaration_List()
   * @model containment="true"
   * @generated
   */
  EList<VariableDecList> getList();

} // VarialbeDeclaration
