/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Dec List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.VariableDecList#getType <em>Type</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.VariableDecList#getVariablenamelist <em>Variablenamelist</em>}</li>
 * </ul>
 *
 * @see org.consensus.homodel.hOModel.HOModelPackage#getVariableDecList()
 * @model
 * @generated
 */
public interface VariableDecList extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getVariableDecList_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.VariableDecList#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Variablenamelist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variablenamelist</em>' containment reference.
   * @see #setVariablenamelist(VariableNameList)
   * @see org.consensus.homodel.hOModel.HOModelPackage#getVariableDecList_Variablenamelist()
   * @model containment="true"
   * @generated
   */
  VariableNameList getVariablenamelist();

  /**
   * Sets the value of the '{@link org.consensus.homodel.hOModel.VariableDecList#getVariablenamelist <em>Variablenamelist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variablenamelist</em>' containment reference.
   * @see #getVariablenamelist()
   * @generated
   */
  void setVariablenamelist(VariableNameList value);

} // VariableDecList
