/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel.impl;

import org.consensus.homodel.hOModel.HOModelPackage;
import org.consensus.homodel.hOModel.NormalVariable;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Normal Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NormalVariableImpl extends VariableImpl implements NormalVariable
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NormalVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HOModelPackage.Literals.NORMAL_VARIABLE;
  }

} //NormalVariableImpl
