/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel.impl;

import java.util.Collection;

import org.consensus.homodel.hOModel.HOModelPackage;
import org.consensus.homodel.hOModel.Statement;
import org.consensus.homodel.hOModel.Variable;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.impl.StatementImpl#getVar <em>Var</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.impl.StatementImpl#getExp <em>Exp</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.impl.StatementImpl#getStatement <em>Statement</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StatementImpl extends MinimalEObjectImpl.Container implements Statement
{
  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected EList<Variable> var;

  /**
   * The cached value of the '{@link #getExp() <em>Exp</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExp()
   * @generated
   * @ordered
   */
  protected EList<EObject> exp;

  /**
   * The cached value of the '{@link #getStatement() <em>Statement</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStatement()
   * @generated
   * @ordered
   */
  protected EList<Statement> statement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HOModelPackage.Literals.STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Variable> getVar()
  {
    if (var == null)
    {
      var = new EObjectContainmentEList<Variable>(Variable.class, this, HOModelPackage.STATEMENT__VAR);
    }
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EObject> getExp()
  {
    if (exp == null)
    {
      exp = new EObjectContainmentEList<EObject>(EObject.class, this, HOModelPackage.STATEMENT__EXP);
    }
    return exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Statement> getStatement()
  {
    if (statement == null)
    {
      statement = new EObjectContainmentEList<Statement>(Statement.class, this, HOModelPackage.STATEMENT__STATEMENT);
    }
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HOModelPackage.STATEMENT__VAR:
        return ((InternalEList<?>)getVar()).basicRemove(otherEnd, msgs);
      case HOModelPackage.STATEMENT__EXP:
        return ((InternalEList<?>)getExp()).basicRemove(otherEnd, msgs);
      case HOModelPackage.STATEMENT__STATEMENT:
        return ((InternalEList<?>)getStatement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HOModelPackage.STATEMENT__VAR:
        return getVar();
      case HOModelPackage.STATEMENT__EXP:
        return getExp();
      case HOModelPackage.STATEMENT__STATEMENT:
        return getStatement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HOModelPackage.STATEMENT__VAR:
        getVar().clear();
        getVar().addAll((Collection<? extends Variable>)newValue);
        return;
      case HOModelPackage.STATEMENT__EXP:
        getExp().clear();
        getExp().addAll((Collection<? extends EObject>)newValue);
        return;
      case HOModelPackage.STATEMENT__STATEMENT:
        getStatement().clear();
        getStatement().addAll((Collection<? extends Statement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HOModelPackage.STATEMENT__VAR:
        getVar().clear();
        return;
      case HOModelPackage.STATEMENT__EXP:
        getExp().clear();
        return;
      case HOModelPackage.STATEMENT__STATEMENT:
        getStatement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HOModelPackage.STATEMENT__VAR:
        return var != null && !var.isEmpty();
      case HOModelPackage.STATEMENT__EXP:
        return exp != null && !exp.isEmpty();
      case HOModelPackage.STATEMENT__STATEMENT:
        return statement != null && !statement.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //StatementImpl
