/**
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.hOModel.impl;

import org.consensus.homodel.hOModel.HOModelPackage;
import org.consensus.homodel.hOModel.VariableDecList;
import org.consensus.homodel.hOModel.VariableNameList;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable Dec List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.consensus.homodel.hOModel.impl.VariableDecListImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.consensus.homodel.hOModel.impl.VariableDecListImpl#getVariablenamelist <em>Variablenamelist</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VariableDecListImpl extends MinimalEObjectImpl.Container implements VariableDecList
{
  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final String TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected String type = TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getVariablenamelist() <em>Variablenamelist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariablenamelist()
   * @generated
   * @ordered
   */
  protected VariableNameList variablenamelist;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VariableDecListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HOModelPackage.Literals.VARIABLE_DEC_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(String newType)
  {
    String oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HOModelPackage.VARIABLE_DEC_LIST__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableNameList getVariablenamelist()
  {
    return variablenamelist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariablenamelist(VariableNameList newVariablenamelist, NotificationChain msgs)
  {
    VariableNameList oldVariablenamelist = variablenamelist;
    variablenamelist = newVariablenamelist;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST, oldVariablenamelist, newVariablenamelist);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariablenamelist(VariableNameList newVariablenamelist)
  {
    if (newVariablenamelist != variablenamelist)
    {
      NotificationChain msgs = null;
      if (variablenamelist != null)
        msgs = ((InternalEObject)variablenamelist).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST, null, msgs);
      if (newVariablenamelist != null)
        msgs = ((InternalEObject)newVariablenamelist).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST, null, msgs);
      msgs = basicSetVariablenamelist(newVariablenamelist, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST, newVariablenamelist, newVariablenamelist));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST:
        return basicSetVariablenamelist(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HOModelPackage.VARIABLE_DEC_LIST__TYPE:
        return getType();
      case HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST:
        return getVariablenamelist();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HOModelPackage.VARIABLE_DEC_LIST__TYPE:
        setType((String)newValue);
        return;
      case HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST:
        setVariablenamelist((VariableNameList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HOModelPackage.VARIABLE_DEC_LIST__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST:
        setVariablenamelist((VariableNameList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HOModelPackage.VARIABLE_DEC_LIST__TYPE:
        return TYPE_EDEFAULT == null ? type != null : !TYPE_EDEFAULT.equals(type);
      case HOModelPackage.VARIABLE_DEC_LIST__VARIABLENAMELIST:
        return variablenamelist != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //VariableDecListImpl
