/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HOModelStandaloneSetup extends HOModelStandaloneSetupGenerated {

	public static void doSetup() {
		new HOModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
