/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHOModelScopeProvider extends DelegatingScopeProvider {
}
