/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HOModelUiModule extends AbstractHOModelUiModule {

	public HOModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
