/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HOModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/consensus/homodel/parser/antlr/internal/InternalHOModel.tokens");
	}
}
