/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.parser.antlr;

import com.google.inject.Inject;
import org.consensus.homodel.parser.antlr.internal.InternalHOModelParser;
import org.consensus.homodel.services.HOModelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HOModelParser extends AbstractAntlrParser {

	@Inject
	private HOModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHOModelParser createParser(XtextTokenStream stream) {
		return new InternalHOModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Algorithm";
	}

	public HOModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HOModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
