/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.consensus.homodel.HOModelRuntimeModule;
import org.consensus.homodel.HOModelStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HOModelIdeSetup extends HOModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HOModelRuntimeModule(), new HOModelIdeModule()));
	}
	
}
