/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.ui.tests;

import com.google.inject.Injector;
import org.consensus.homodel.ui.internal.HomodelActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class HOModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HomodelActivator.getInstance().getInjector("org.consensus.homodel.HOModel");
	}

}
