/*
 * generated by Xtext 2.26.0
 */
package org.consensus.homodel.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractHOModelValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.consensus.homodel.hOModel.HOModelPackage.eINSTANCE);
		return result;
	}
}
